// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXVqxigOSmSI4GSbxuPBmWmEy_8nX4jWM',
    appId: '1:291474849498:android:392c0f755f720a3ddd2fe3',
    messagingSenderId: '291474849498',
    projectId: 'starparking-zona-azul',
    databaseURL: 'https://starparking-zona-azul-default-rtdb.firebaseio.com',
    storageBucket: 'starparking-zona-azul.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4s9oCnHbG9dsMBwF8rjAkPl-TXDtf_dU',
    appId: '1:291474849498:ios:768059ba3ad2d515dd2fe3',
    messagingSenderId: '291474849498',
    projectId: 'starparking-zona-azul',
    databaseURL: 'https://starparking-zona-azul-default-rtdb.firebaseio.com',
    storageBucket: 'starparking-zona-azul.appspot.com',
    iosClientId: '291474849498-6hje53lfmphm0j9qa491cornfk8pu5pn.apps.googleusercontent.com',
    iosBundleId: 'com.example.starParkingAppCidadao',
  );
}
